name: "Pull Request Labeler"
on:
  pull_request_target:
    types:
      - opened

jobs:
  triage:
    permissions:
#       actions: none
#       checks: none
      contents: read
#       deployments: none
#       id-token: none
#       issues: none
#       discussions: none
#       packages: none
#       pages: none
      pull-requests: write
#       repository-projects: none
#       security-events: none
#       statuses: none
      
    runs-on: ubuntu-latest
    steps:
    - uses: AnuragThePathak/labeler-copy@v1.9.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yaml
        sync-labels: false

